# Base for ST:OW mutant SpawnOnApproach triggers

- type: entity
  id: MutantSpawnerBase
  parent: MarkerBase
  abstract: true
  suffix: ST:OW, Mutant Spawner
  components:
    - type: ApproachTrigger
      range: 33

    - type: Sprite
      layers:
        - state: blue
        - sprite: Mobs/Aliens/Xenos/burrower.rsi
          state: crit
        - state: ai
          
    - type: SpawnOnApproach
      minAmount: 1
      maxAmount: 1

      minOffset: 5 # Min tiles from spawner
      maxOffset: 8 # Max tiles from spawner
      
      spawnNearPlayers: false
      minPlayerDistance: 5 # Min distance from player

      chance: 1 # 100% spawn chance
      cooldown: 1800 # In seconds, 30 minutes after a SUCCESSFUL spawn
      failureCooldown: 600 # In seconds, 10 minutes after a FAILED spawn
      chanceIncreaseOnFailure: 0.10 # +10% per failed spawn roll
      timeoutOnRoll: true # Cooldown always applies